name: spark
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  build_runner: ^2.4.8
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.15.9
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^5.4.1
  expandable_text: ^2.3.0
  firebase_auth: ^4.17.9
  firebase_core: ^2.27.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_facebook_auth: ^6.1.1
  flutter_svg: ^2.0.10+1
  font_awesome_flutter: ^10.7.0
  freezed: ^2.4.7
  freezed_annotation: ^2.4.1
  get: ^4.6.6
  google_sign_in: ^6.2.1
  intl: ^0.19.0
  json_annotation: ^4.8.1
  lottie: ^3.1.0
  persistent_bottom_nav_bar: ^5.0.2
  photo_view: ^0.14.0
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  uuid: ^4.3.3
  youtube_player_flutter: ^9.0.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - .env
    - assets/animations/
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/lato/Lato-Light.ttf
          weight: 300
        - asset: assets/fonts/lato/Lato-Regular.ttf
          weight: 400
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
        - asset: assets/fonts/lato/Lato-Bold.ttf
          weight: 700
          style: italic
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/roboto/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/roboto/Roboto-Bold.ttf
          weight: 700

flutter_assets:
  assets_path: assets/
  output_path: lib/core/utils/
  filename: assets_manager.dart

flutter_launcher_icons:
  image_path: "assets/images/spark_logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
